# --- SAC specific parameters ---

# action_selector: "soft_policies"
action_selector: "multinomial"
mask_before_softmax: True

epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "episode"

buffer_size: 500000
# update the target network every {} episodes
target_update_interval_or_tau: 0.005

obs_agent_id: True
obs_last_action: False # 连续动作不能采用one hot id action
obs_individual_obs: False
mixer: "linear_abs_mixer"

agent: "isac"
# use the madddpg_learner to train
mac: "isac_mac"
gama: 0.99
tau: 0.005

reg: 0.001
batch_size: 32
epochs: 1 # For behavior clone 
lr: 0.0003
use_rnn: True

standardise_returns: False
standardise_rewards: True

learner: "maiq_continuous_learner_online"
agent_output_type: "None"
hidden_dim: 128
v_net: "isac_v_net"
q_net: "isac_q_net"
sac_alpha: 0.001
grad_norm_clip: 10
task_type: "continuous"

use_wandb: True
results_save_dir: './results/'
load_dataset_dir: 'dataset/mpe_SimpleTag-v0__50.pkl'
alpha: 0.5
name: "maiq_c"
use_tanh: True
is_bc: False 