env: "gymma"

env_args:
  key: null
  time_limit: 100
  pretrained_wrapper: null
  # discrete_action_space: False
  # pretrained_wrapper: "PretrainedTag"

test_greedy: True
test_nepisode: 100
test_interval: 1000
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
t_max: 2050000

